### ISSUE TITLE
Configure for line wrapping

### ISSUE THREAD

**Issue by martinthomson** [mnot/rfc-http-validate#5]
Having the RFC 8792 note in every example can be tedious.    A config option or command-line argument that enabled this globally would be useful.

I'm looking at the HTTP extensions repo and there are some drafts that really suffer from this badly.  We'd probably want that to be on a per-draft basis though.  That would bias toward a configuration option in the draft to drive a command-line argument choice rather than the global configuration file that might affect other drafts.

**Comment by mnot** [comment]
My understanding is that 8792 requires the note.

**Comment by martinthomson** [comment]
That's silly.  The examples in the signatures draft all contain the header, which adds a ton of useless noise.  I know why, but that mostly boils down to "we can't change the XML format and the TXT format is ridiculous".  Maybe the right answer is an attribute on the element or even `<artset>`.

As this is probably something for the RSWG to address, if you don't want to track this, then close it.
